services:
  mysql:
    image: mysql:8.4.0
    container_name: mungstore-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mungstore
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql

  redis:
    image: redis:7.2.4
    container_name: mungstore-redis
    ports:
      - 6379:6379

  zookeeper:
    image: zookeeper
    container_name: mungstore-zookeeper
    ports:
      - 2181:2181

  kafka:
    image: bitnami/kafka
    container_name: mungstore-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock