services:
  mysql:
    image: mysql:8.4.0
    container_name: mungstore-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mungstore
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - mungstore

  redis:
    image: redis:7.2.4
    container_name: mungstore-redis
    ports:
      - 6379:6379
    networks:
      - mungstore

networks:
  mungstore:
    driver: bridge