server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.137.1:3306/mungstore?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: mungstore_user
    password: 1111

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
      org.hibernate.envers:
        audit_table_suffix: History
        revision_field_name: revisionId
        revision_type_field_name: revisionType
        store_data_at_delete: true
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: false

  main:
    allow-bean-definition-overriding: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  redis:
    host: 192.168.137.1
    port: 6379

logging:
  file:
    name: app.log
    path: .
  level:
    root: info
  org.hibernate.SQL: debug
  # org.hibernate.type: trace

feign:
  okhttp:
    enable: true
  mailgun:
    key: "None"

jwt:
  key: "/VLfdrwEn0MZScSqq6En7NMOW9rF7SQHN7LiWGCG21g="

kakao:
  dev:
      host: "http://localhost:8080"
      secret-key: "DEV892EC0FB978849194C578B9AE3D028C7826DF"
      cid: "TC0ONETIME"
