CREATE TABLE PRODUCT_HISTORY (
    PRODUCT_ID          BIGINT          NOT NULL,
    REVISION_ID         BIGINT          AUTO_INCREMENT,
    REVISION_TYPE       TINYINT(3)      NULL DEFAULT NULL,
    NAME                VARCHAR(100)    NOT NULL,
    DETAILS             LONGTEXT,
    PRICE               INTEGER         NOT NULL,
    COMP_ID             BIGINT,
    ACTIVE_FOR_SALE     BIT             NOT NULL,
    CREATED_BY          BIGINT,
    CREATED_AT          DATETIME(6)     NOT NULL,
    LAST_MODIFIED_BY    BIGINT,
    LAST_MODIFIED_AT    DATETIME(6)     NOT NULL,
    USE_YN              BIT,
    PRIMARY KEY (PRODUCT_ID, REVISION_ID) USING BTREE,
    INDEX PRODUCT_HISTORY_INDEX (REVISION_ID) USING BTREE,
    CONSTRAINT PRODUCT_HISTORY_FK FOREIGN KEY (REVISION_ID) REFERENCES REVISION_HISTORY (REVISION_ID) ON UPDATE NO ACTION ON DELETE NO ACTION
);