CREATE TABLE STOCK (
    STOCK_ID            BIGINT          AUTO_INCREMENT PRIMARY KEY,
    SKU_ID              VARCHAR(20)     NOT NULL UNIQUE,
    OPTION_ID           BIGINT          NOT NULL,
    QUANTITY            INTEGER         DEFAULT 0,
    CREATED_AT          DATETIME(6)     NOT NULL,
    LAST_MODIFIED_AT    DATETIME(6)     NOT NULL
);


INSERT INTO STOCK (STOCK_ID, SKU_ID, OPTION_ID, QUANTITY, CREATED_AT, LAST_MODIFIED_AT) VALUES (1, 'pd1-op1', 1, 12, NOW(), NOW());
INSERT INTO STOCK (STOCK_ID, SKU_ID, OPTION_ID, QUANTITY, CREATED_AT, LAST_MODIFIED_AT) VALUES (2, 'pd1-op2', 2, 22, NOW(), NOW());
INSERT INTO STOCK (STOCK_ID, SKU_ID, OPTION_ID, QUANTITY, CREATED_AT, LAST_MODIFIED_AT) VALUES (3, 'pd2-op1', 3, 15, NOW(), NOW());
INSERT INTO STOCK (STOCK_ID, SKU_ID, OPTION_ID, QUANTITY, CREATED_AT, LAST_MODIFIED_AT) VALUES (4, 'pd2-op2', 4, 52, NOW(), NOW());