CREATE TABLE ORDERS (
    ORDER_ID            BIGINT          AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID           BIGINT          NOT NULL,
    DELIVERY_ID         BIGINT          NOT NULL UNIQUE,
    STATUS              VARCHAR(20)     NOT NULL,
    TOTAL_PRICE         INTEGER         NOT NULL,
    DISCOUNT_PRICE      INTEGER         NOT NULL,
    CREATED_BY          BIGINT,
    CREATED_AT          DATETIME(6)     NOT NULL,
    LAST_MODIFIED_BY    BIGINT,
    LAST_MODIFIED_AT    DATETIME(6)     NOT NULL
);

CREATE TABLE ORDERS_HISTORY (
    LOG_ID              BIGINT          AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID            BIGINT,
    MEMBER_ID           BIGINT,
    DELIVERY_ID         BIGINT,
    STATUS              VARCHAR(20),
    TOTAL_PRICE         INTEGER,
    DISCOUNT_PRICE      INTEGER,
    CREATED_BY          BIGINT,
    CREATED_AT          DATETIME(6),
    LAST_MODIFIED_BY    BIGINT,
    LAST_MODIFIED_AT    DATETIME(6)
);