DROP TABLE ORDERS_HISTORY;

CREATE TABLE ORDERS_HISTORY (
    ORDER_ID            BIGINT          NOT NULL,
    REVISION_ID         BIGINT          NOT NULL AUTO_INCREMENT,
    REVISION_TYPE       TINYINT(3)      NULL DEFAULT NULL,
    MEMBER_ID           BIGINT          NOT NULL,
    DELIVERY_ID         BIGINT          NOT NULL,
    STATUS              VARCHAR(20)     NOT NULL,
    TOTAL_PRICE         INTEGER         NOT NULL,
    DISCOUNT_PRICE      INTEGER         NOT NULL,
    CREATED_BY          BIGINT,
    CREATED_AT          DATETIME(6)     NOT NULL,
    LAST_MODIFIED_BY    BIGINT,
    LAST_MODIFIED_AT    DATETIME(6)     NOT NULL,
    PRIMARY KEY (ORDER_ID, REVISION_ID) USING BTREE,
    INDEX ORDERS_HISTORY_INDEX (REVISION_ID) USING BTREE,
    CONSTRAINT ORDERS_HISTORY_FK FOREIGN KEY (REVISION_ID) REFERENCES REVISION_HISTORY (REVISION_ID) ON UPDATE NO ACTION ON DELETE NO ACTION
);