DROP TABLE ORDER_ITEM_HISTORY;

CREATE TABLE ORDER_ITEM_HISTORY (
    ORDER_ITEM_ID       BIGINT          NOT NULL,
    REVISION_ID         BIGINT          NOT NULL AUTO_INCREMENT,
    REVISION_TYPE       TINYINT(3)      NULL DEFAULT NULL,
    ORDER_ID            BIGINT          NOT NULL,
    PRODUCT_ID          BIGINT          NOT NULL,
    STOCK_ID            BIGINT          NOT NULL,
    OPTION_ID           BIGINT          NOT NULL,
    MEMBER_ID           BIGINT          NOT NULL,
    ORDER_PRICE         INTEGER         NOT NULL,
    QUANTITY            INTEGER         NOT NULL,
    CONTENTS            VARCHAR(300),
    STATUS              VARCHAR(20)     NOT NULL,
    CREATED_BY          BIGINT,
    CREATED_AT          DATETIME(6)     NOT NULL,
    LAST_MODIFIED_BY    BIGINT,
    LAST_MODIFIED_AT    DATETIME(6)     NOT NULL,
    PRIMARY KEY (ORDER_ITEM_ID, REVISION_ID) USING BTREE,
    INDEX ORDER_ITEM_HISTORY_INDEX (REVISION_ID) USING BTREE,
    CONSTRAINT ORDER_ITEM_HISTORY_FK FOREIGN KEY (REVISION_ID) REFERENCES REVISION_HISTORY (REVISION_ID) ON UPDATE NO ACTION ON DELETE NO ACTION
);