DROP TABLE DELIVERY_HISTORY;

CREATE TABLE DELIVERY_HISTORY (
    DELIVERY_ID         BIGINT          NOT NULL,
    REVISION_ID         BIGINT          NOT NULL AUTO_INCREMENT,
    REVISION_TYPE       TINYINT(3)      NULL DEFAULT NULL,
    SHIPPER             VARCHAR(50),
    TRACKING_NO         VARCHAR(50),
    TEL1                VARCHAR(11)     NOT NULL,
    TEL2                VARCHAR(11)     NOT NULL,
    ZIPCODE             VARCHAR(6)      NOT NULL,
    CITY                VARCHAR(20)     NOT NULL,
    STREET              VARCHAR(50)     NOT NULL,
    STATUS              VARCHAR(20)     NOT NULL,
    CREATED_BY          BIGINT,
    CREATED_AT          DATETIME(6)     NOT NULL,
    LAST_MODIFIED_BY    BIGINT,
    LAST_MODIFIED_AT    DATETIME(6)     NOT NULL,
    PRIMARY KEY (DELIVERY_ID, REVISION_ID) USING BTREE,
    INDEX DELIVERY_HISTORY_INDEX (REVISION_ID) USING BTREE,
    CONSTRAINT DELIVERY_HISTORY_FK FOREIGN KEY (REVISION_ID) REFERENCES REVISION_HISTORY (REVISION_ID) ON UPDATE NO ACTION ON DELETE NO ACTION
);