CREATE TABLE STOCK_HISTORY (
    STOCK_ID            BIGINT          NOT NULL,
    REVISION_ID         BIGINT          NOT NULL AUTO_INCREMENT,
    REVISION_TYPE       TINYINT(3)      NULL DEFAULT NULL,
    SKU_ID              VARCHAR(20)     NOT NULL,
    OPTION_ID           BIGINT          NOT NULL,
    QUANTITY            INTEGER         NOT NULL,
    CREATED_AT          DATETIME(6)     NOT NULL,
    LAST_MODIFIED_AT    DATETIME(6)     NOT NULL,
    PRIMARY KEY (STOCK_ID, REVISION_ID) USING BTREE,
    INDEX STOCK_HISTORY_INDEX (REVISION_ID) USING BTREE,
    CONSTRAINT STOCK_HISTORY_FK FOREIGN KEY (REVISION_ID) REFERENCES REVISION_HISTORY (REVISION_ID) ON UPDATE NO ACTION ON DELETE NO ACTION
);