CREATE TABLE PAYMENT_KAKAO_LOG (
    AID                 VARCHAR(50) PRIMARY KEY,
    TID                 VARCHAR(50),
    CID                 VARCHAR(50),
    SID                 VARCHAR(50),
    PARTNER_ORDER_ID    VARCHAR(100),
    PARTNER_USER_ID     VARCHAR(100),
    PAYMENT_METHOD_TYPE VARCHAR(5),
    TOTAL               INTEGER,
    TAX_FREE            INTEGER,
    VAT                 INTEGER,
    POINT               INTEGER,
    DISCOUNT            INTEGER,
    GREEN_DEPOSIT       INTEGER,
    KAKAOPAY_PURCHASE_CORP        VARCHAR(10),
    KAKAOPAY_PURCHASE_CORP_CODE   VARCHAR(3),
    KAKAOPAY_ISSUER_CORP          VARCHAR(10),
    KAKAOPAY_ISSUER_CORP_CODE     VARCHAR(3),
    BIN                           VARCHAR(10),
    CARD_TYPE                     VARCHAR(5),
    INSTALL_MONTH                 VARCHAR(2),
    APPROVED_ID                   VARCHAR(50),
    CARD_MID                      VARCHAR(50),
    INTEREST_FREE_INSTALL         VARCHAR(1),
    INSTALLMENT_TYPE              VARCHAR(30),
    CARD_ITEM_CODE                VARCHAR(3),
    ITEM_NAME         VARCHAR(100),
    ITEM_CODE         VARCHAR(100),
    QUANTITY          INTEGER,
    CREATED_AT        DATETIME(6),
    APPROVED_AT       DATETIME(6),
    PAYLOAD           VARCHAR(100)
);