ALTER TABLE MEMBER
MODIFY COLUMN CREATED_BY BIGINT;

ALTER TABLE MEMBER
MODIFY COLUMN LAST_MODIFIED_BY BIGINT;

ALTER TABLE MEMBER_LOG
MODIFY COLUMN CREATED_BY BIGINT;

ALTER TABLE MEMBER_LOG
MODIFY COLUMN LAST_MODIFIED_BY BIGINT;
