ALTER TABLE PRODUCT
MODIFY COLUMN CREATED_BY BIGINT;

ALTER TABLE PRODUCT
MODIFY COLUMN LAST_MODIFIED_BY BIGINT;

ALTER TABLE PRODUCT_LOG
MODIFY COLUMN CREATED_BY BIGINT;

ALTER TABLE PRODUCT_LOG
MODIFY COLUMN LAST_MODIFIED_BY BIGINT;
