services:
  zookeeper:
    image: zookeeper
    container_name: mungstore-zookeeper
    ports:
      - 2181:2181
    networks:
      - mungstore

  kafka:
    image: bitnami/kafka
    container_name: mungstore-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mungstore

  api:
    image: mungstore-api:1.0.0
    container_name: mungstore-api
    ports:
      - "8080:8080"
    networks:
      - mungstore

  consumer:
    image: mungstore-consumer:1.0.0
    container_name: mungstore-consumer
    ports:
      - "8081:8081"
    networks:
      - mungstore

networks:
  mungstore:
    driver: bridge